// <auto-generated />
using System;
using AspNetCore_MVC_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetCore_MVC_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250216090059_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspNetCore_MVC_Project.Models.Control.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("FactoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("AspNetCore_MVC_Project.Models.Control.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("AspNetCore_MVC_Project.Models.Control.OptionBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameController")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OptionBlocks");
                });

            modelBuilder.Entity("AspNetCore_MVC_Project.Models.Control.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FactoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("FactoryId1")
                        .HasColumnType("integer");

                    b.Property<int>("OptionBlockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("FactoryId1");

                    b.HasIndex("OptionBlockId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("AspNetCore_MVC_Project.Models.Control.ApplicationUser", b =>
                {
                    b.HasOne("AspNetCore_MVC_Project.Models.Control.Factory", "Factory")
                        .WithMany("Users")
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("AspNetCore_MVC_Project.Models.Control.Purchase", b =>
                {
                    b.HasOne("AspNetCore_MVC_Project.Models.Control.Factory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AspNetCore_MVC_Project.Models.Control.Factory", null)
                        .WithMany("Purchases")
                        .HasForeignKey("FactoryId1");

                    b.HasOne("AspNetCore_MVC_Project.Models.Control.OptionBlock", "OptionBlock")
                        .WithMany("Purchases")
                        .HasForeignKey("OptionBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("OptionBlock");
                });

            modelBuilder.Entity("AspNetCore_MVC_Project.Models.Control.Factory", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AspNetCore_MVC_Project.Models.Control.OptionBlock", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
